const AUTH_QUERY_KEYS = {
  POST_KAKAO: ['POST_KAKAO'],
  POST_KAKAO_OAUTH: ['POST_KAKAO_OAUTH'],
  POST_OAUTH_KAKAO: ['POST_OAUTH_KAKAO'],
  POST_JOIN_WITHOUT_PET: ['POST_JOIN_WITHOUT_PET'],
  POST_AVAILABLE_NICKNAME: ['POST_AVAILABLE_NICKNAME'],
  GET_BREED_LIST: ['GET_BREED_LIST'],
  POST_JOIN_WITH_PET: ['POST_JOIN_WITH_PET'],
  GET_USER_PET_INFO: ['GET_USER_PET_INFO'],
  POST_USER_PET: ['POST_USER_PET'],
  POST_USER_PET_INFO: ['POST_USER_PET_INFO'],
  DELETE_USER_PET: ['DELETE_USER_PET'],
  GET_USER_VALIDATE: ['GET_USER_VALIDATE'],
  GET_USER_MYPAGE: ['GET_USER_MYPAGE'],
  GET_USER_WITHDRAW_INFO: ['GET_USER_WITHDRAW_INFO'],
  DELETE_USER_INFO: ['DELETE_USER_INFO'],
  POST_VERIFY_EMAIL_CODE: ['POST_VERIFY_EMAIL_CODE'],
  POST_CONFIRM_EMAIL: ['POST_CONFIRM_EMAIL'],
  POST_SIGNUP: ['POST_SIGNUP'],
  POST_LOGIN: ['POST_LOGIN'],
  POST_RESET_PASSWORD: ['POST_RESET_PASSWORD'],
  POST_RESET_PASSWORD_CONFIRM: ['POST_RESET_PASSWORD_CONFIRM'],
  POST_INTEREST: ['POST_INTEREST'],
  GET_USER_PROFILE: ['GET_USER_PROFILE'],
  PATCH_USER_PROFILE: ['PATCH_USER_PROFILE'],
  POST_USER_PROFILE_IMAGE: ['POST_USER_PROFILE_IMAGE'],
  DELETE_USER_PROFILE_IMAGE: ['DELETE_USER_PROFILE_IMAGE'],
  POST_MARKETING_CONSENT: ['POST_MARKETING_CONSENT'],
};
const COMPANY_QUERY_KEYS = {
  GET_CLINIC: ['GET_CLINIC'],
  GET_CLINIC_CLINICID: ['GET_CLINIC_CLINICID'],
  GET_COMPANY_SEARCH: ['GET_COMPANY_SEARCH'],
  GET_COMPANY_DETAIL: ['GET_COMPANY_DETAIL'],
  GET_COMPANY_ALL: ['GET_COMPANY_ALL'],
  GET_RECENT_COMPANY: ['GET_RECENT_COMPANY'],
  GET_RECOMMENDED_COMPANY: ['GET_RECOMMENDED_COMPANY'],
};

const REVIEW_QUERY_KEYS = {
  POST_CLINIC_REVIEW: ['POST_CLINIC_REVIEW'],
  GET_CLINIC_REVIEWS: ['GET_CLINIC_REVIEWS'],
  GET_COMPANY_REVIEWS: ['GET_COMPANY_REVIEWS'],
  GET_REVIEW_DETAIL: ['GET_REVIEW_DETAIL'],
  PUT_REVIEW: ['PUT_REVIEW'],
};
const ESTIMATE_QUERY_KEYS = {
  GET_USER_ESTIMATE_GENERAL_GROOMING_PETS: ['GET_USER_ESTIMATE_GENERAL_GROOMING_PETS'],
  GET_USER_ESTIMATE_GENERAL_GROOMING: ['GET_USER_ESTIMATE_GENERAL_GROOMING'],
  GET_USER_ESTIMATE_GENERAL_CARE_PETS: ['GET_USER_ESTIMATE_GENERAL_CARE_PETS'],
  GET_USER_ESTIMATE_GENERAL_CARE: ['GET_USER_ESTIMATE_GENERAL_CARE'],
  GET_USER_ESTIMATE_DESIGNATION_GROOMING_PETS: ['GET_USER_ESTIMATE_DESIGNATION_GROOMING_PETS'],
  GET_USER_ESTIMATE_DESIGNATION_GROOMING: ['GET_USER_ESTIMATE_DESIGNATION_GROOMING'],
  GET_USER_ESTIMATE_DESIGNATION_CARE_PETS: ['GET_USER_ESTIMATE_DESIGNATION_CARE_PETS'],
  GET_USER_ESTIMATE_DESIGNATION_CARE: ['GET_USER_ESTIMATE_DESIGNATION_CARE'],
  POST_ESTIMATE_GROOMER_USER_INFO: [' POST_USER_ESTIMATE_GROOMER_USER_INFO'],
  POST_ESTIMATES_GROOMING: ['POST_USER_ESTIMATES_GROOMING'],
  POST_USER_ESTIMATES_VET_USER_INFO: ['POST_USER_ESTIMATES_VET_USER_INFO'],
  POST_USER_ESTIMATE_CARE: ['POST_USER_ESTIMATE_CARE'],
  GET_USER_PROFILE_INFO: ['GET_USER_PROFILE_INFO'],
  POST_USER_PROFILE_INFO: ['POST_USER_PROFILE_INFO'],
  GET_USER_ESTIMATE_GROOMERS_DETAIL: ['GET_USER_ESTIMATE_GROOMERS_DETAIL'],
  GET_USER_ESTIMATES_VETS_DETAIL: ['GET_USER_ESTIMATES_VETS_DETAIL'],
  GET_USER_ESTIMATES_REQUEST_GROOMING: ['GET_USER_ESTIMATES_REQUEST_GROOMING'],
  GET_USER_ESTIMATES_REQUEST_CARE: ['GET_USER_ESTIMATES_REQUEST_CARE'],
  POST_ESTIMATE_CANCEL_GROOMING: ['POST_ESTIMATE_CANCEL_GROOMING'],
  POST_ESTIMATE_CANCEL_CARE: ['POST_ESTIMATE_CANCEL_CARE'],
};

const PAYMENT_QUERY_KEYS = {
  GET_PAYMENT_GROOMING_HISTORY_LIST: ['GET_PAYMENT_GROOMING_HISTORY_LIST'],
  GET_PAYMENT_CARE_HISTORY_LIST: ['GET_PAYMENT_CARE_HISTORY_LIST'],
  GET_PAYMENT_HISTORY_DETAIL: ['GET_PAYMENT_HISTORY_DETAIL'],
  POST_PAYMENT_ORDER: ['POST_PAYMENT_ORDER'],
  POST_PAYMENT_VALIDATE: ['POST_PAYMENT_VALIDATE'],
};

const RESERVATION_QUERY_KEYS = {
  CREATE_RESERVATION: ['CREATE_RESERVATION'],
  GET_RESERVATIONS: ['GET_RESERVATIONS'],
};

const CHAT_QUERY_KEYS = {
  GET_CHAT_USER_GROOMER_LIST: ['GET_CHAT_USER_GROOMER_LIST'],
  GET_CHAT_USER_VET_LIST: ['GET_CHAT_USER_VET_LIST'],
  GET_CHAT_WITH: ['GET_CHAT_WITH'],
  POST_CHAT_MESSAGES: ['POST_CHAT_MESSAGES'],
  DELETE_CHAT_DELETE: ['DELETE_CHAT_DELETE'],
  GET_CHAT_START: ['GET_CHAT_START'],
};

const HOME_QUERY_KEYS = {
  GET_USER_SHOPS: ['GET_USER_SHOPS'],
  GET_USER_VETS: ['GET_USER_VETS'],
};

const DETAIL_QUERY_KEYS = {
  GET_USER_GROOMERS_DETAIL: ['GET_USER_GROOMERS_DETAIL'],
  GET_USER_VETS_DETAIL: ['GET_USER_VETS_DETAIL'],
  GET_USER_SHOP_DETAIL: ['GET_USER_SHOP_DETAIL'],
};
const SEARCH_QUERY_KEYS = {
  GET_USER_SEARCH_VET: ['GET_USER_SEARCH_VET'],
  GET_USER_SEARCH_GROOMER: ['GET_USER_SEARCH_GROOMER'],
};

const PROGRAM_QUERY_KEYS = {
  GET_PROGRAM_COMPANY: ['GET_PROGRAM_COMPANY'],
  GET_PROGRAM_DETAIL: ['GET_PROGRAM_DETAIL'],
};

export const QUERY_KEYS = {
  ...AUTH_QUERY_KEYS,
  ...COMPANY_QUERY_KEYS,
  ...ESTIMATE_QUERY_KEYS,
  ...REVIEW_QUERY_KEYS,
  ...PAYMENT_QUERY_KEYS,
  ...RESERVATION_QUERY_KEYS,
  ...CHAT_QUERY_KEYS,
  ...HOME_QUERY_KEYS,
  ...DETAIL_QUERY_KEYS,
  ...SEARCH_QUERY_KEYS,
  ...PROGRAM_QUERY_KEYS,
} as const;
